In [1]:
import numpy as np

# 行列 A と B の定義
A = np.array([[0, 1], [2, 3], [4, 5]])
B = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

# 行列の積を計算
C = np.dot(A, B)

# 結果を表示
print("行列の積 C:")
print(C)

# 行列 C の要素の最大値を計算
max_value = np.max(C)
print("行列 C の要素の最大値:", max_value)

行列の積 C:
[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
行列 C の要素の最大値: 47
